# Generated by Django 6.0.3 on 2026-03-14 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
