# Generated by Django 6.0.3 on 2026-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
